/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-05-15 03:50:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class select_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/project1/hyusik/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/prac1/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/tags/notLogin.tag", Long.valueOf(1589266511036L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1589173211115L));
    _jspx_dependants.put("/WEB-INF/tags/isLogin.tag", Long.valueOf(1589266504704L));
    _jspx_dependants.put("/header/header.jsp", Long.valueOf(1589504935203L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#rank {width: 200px;position: relative;top: -35px;left: 920px;}\r\n");
      out.write("#rank-list {overflow: hidden;width: 300px;height: 20px;margin: 0;}\r\n");
      out.write("#rank-list dd {position: relative;margin: 0;}\r\n");
      out.write("#rank-list ol {position: absolute;top: 0;left: 0;margin: 0;padding: 0;list-style-type: none;}\r\n");
      out.write("#rank-list li {height: 20px;line-height: 20px;}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("    var count = $('#rank-list li').length;\r\n");
      out.write("    var height = $('#rank-list li').height();\r\n");
      out.write("\r\n");
      out.write("    function step(index) {\r\n");
      out.write("        $('#rank-list ol').delay(2000).animate({\r\n");
      out.write("            top: -height * index,\r\n");
      out.write("        }, 500, function() {\r\n");
      out.write("            step((index + 1) % count);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    step(1);\r\n");
      out.write("});\r\n");
      out.write("function ranking(){\r\n");
      out.write("\tif(location=='http://localhost:8090/prac1/'){\r\n");
      out.write("\tlocation.replace(\"/prac1/main.go\");}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/header/header_style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"ranking()\">\r\n");
      out.write("<header class=\"body\">\r\n");
      out.write("<form name=\"form1\" action=\"");
      out.print(request.getContextPath());
      out.write("/info.go\" method=\"get\">\r\n");
      out.write("<!-- target=\"_blank\" 클릭하면 새창 -->\r\n");
      out.write("<span class=\"logo\"><a href=\"");
      out.print(request.getContextPath());
      out.write("\">휴~ 식</a></span>\t\r\n");
      out.write("  <div id=\"choice\">\r\n");
      out.write("  <!-- http://localhost:8090/kim/header/header_login.jsp?site=? -->\r\n");
      out.write("    <select name=\"site\" id=\"site\" style=\"width:50%;height:30px;\">\r\n");
      out.write("    \t<option selected>선택하세요</option>\r\n");
      out.write("    \t\t<!--");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("-->\r\n");
      out.write("        \t<option value=\"1\">서울 만남의 광장 부산방향</option>\r\n");
      out.write("            <option value=\"2\">죽전휴게소 서울방향</option>\r\n");
      out.write("            <option value=\"3\">기흥휴게소 부산방향</option>\r\n");
      out.write("            <option value=\"4\">안성휴게소 서울방향</option>\r\n");
      out.write("            <option value=\"5\">입장거봉포도휴게소 서울방향</option>\r\n");
      out.write("            <option value=\"6\">망향휴게소 부산방향</option>\r\n");
      out.write("            <option value=\"7\">천안삼거리휴게소 서울방향</option>\r\n");
      out.write("            <option value=\"8\">천안호두휴게소 부산방향</option>\r\n");
      out.write("            <option value=\"9\">청주휴게소 서울방향</option>\r\n");
      out.write("            <option value=\"10\">옥산휴게소 부산방향</option>\r\n");
      out.write("            <option value=\"11\">죽암휴게소 서울방향</option>\r\n");
      out.write("            <option value=\"12\">죽암휴게소 부산방향</option>\r\n");
      out.write("            <option value=\"13\">신탄진휴게소 서울방향</option>\r\n");
      out.write("    </select>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"찾기\" style=\"height:30px;\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<nav class=\"nav\">\r\n");
      out.write("\t\t\t<ul class=\"list\">\r\n");
      out.write("\t\t\t\t<!-- filter설정하기 -->\r\n");
      out.write("\t\t\t\t<li class=\"list-item\"><a href=\"notice.go\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"list-item\"><a href=\"qna.go\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"list-item\"><a href=\"road.go\">도로 교통 상황</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"list-item\"><a href=\"recommand.go\">추천휴게소</a></li>\r\n");
      out.write("                <li class=\"list-item\"><a href=\"oilprice.go\">추천주유소</a></li>\r\n");
      out.write("                \r\n");
      out.write("                ");
      if (_jspx_meth_u_005fisLogin_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_u_005fnotLogin_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"/main.go\">\r\n");
      out.write("\t<div id=\"rank\">\r\n");
      out.write("\t\t<dl id=\"rank-list\">\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t<li>휴게소 만족도 순위</li>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                <li><a href=\"#\">2 천안삼거리(서울)휴게소 5.0점</a></li>\r\n");
      out.write("                <li><a href=\"#\">3 입장거봉포도(서울)휴게소 5.0점</a></li>\r\n");
      out.write("                <li><a href=\"#\">4 입장거봉포도(서울)휴게소 5.0점</a></li>\r\n");
      out.write("                <li><a href=\"#\">5 입장거봉포도(서울)휴게소 5.0점</a></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("            </dd>\r\n");
      out.write("        </dl>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>다중셀렉트박스메뉴</title>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT LANGUAGE=\"JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("var selectedIndex, selValue, selText, swapValue,swapText,tempValue\r\n");
      out.write("//변수 선언의 꼼수 - eval 함수의 formSelect 변수만 선언하지 않았다. 함수 안에 있지만 전역 변수 처럼 사용하기 위해서...\r\n");
      out.write("\r\n");
      out.write("function selectedForm(idx){\r\n");
      out.write("\tif(idx==\"1\"){\r\n");
      out.write("\t\tformSelect    = document.menuform.first\r\n");
      out.write("\t}else if (idx==\"2\"){\r\n");
      out.write("\t\tformSelect    = document.menuform.second\r\n");
      out.write("\t}else if (idx==\"3\"){\r\n");
      out.write("\t\tformSelect    = document.menuform.third\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"셀렉트메뉴 오류 입니다.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function menu_onclick(idx){\r\n");
      out.write("\r\n");
      out.write("\tselectedForm(idx);\r\n");
      out.write("//eval(\"formSelect = document.menuform.\"+selectName)\r\n");
      out.write("selectedIndex = formSelect.selectedIndex\r\n");
      out.write("\r\n");
      out.write("\tselValue = formSelect.options[selectedIndex].value;\r\n");
      out.write("\tselText  = formSelect.options[selectedIndex].text;\r\n");
      out.write("\tdocument.menuform.text1.value = selValue\r\n");
      out.write("\tdocument.menuform.text2.value = selText\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("var temp\r\n");
      out.write("\ttemp=a\r\n");
      out.write("\ta=b;\r\n");
      out.write("\tb=temp;\t\r\n");
      out.write("alert(\"a=\"+a+\" b=\"+b+\" temp=\"+temp);\r\n");
      out.write("*/\r\n");
      out.write("\r\n");
      out.write("function upper(idx){////////////////////////////// 위로 올리기 함수\r\n");
      out.write("\tselectedForm(idx);\r\n");
      out.write("\tselectedIndex = formSelect.selectedIndex\r\n");
      out.write("\r\n");
      out.write("\tif(selectedIndex==-1){\r\n");
      out.write("\t\talert(\"선택한 메뉴가 없습니다.\"); \r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}else if(selectedIndex==0){\r\n");
      out.write("\t\talert(\"최상위 메뉴를 선택하셨습니다.\"); \r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tselValue  = formSelect.options[selectedIndex].value;\r\n");
      out.write("\t\tselText   = formSelect.options[selectedIndex].text;\r\n");
      out.write("\r\n");
      out.write("\t\tswapValue = formSelect.options[selectedIndex-1].value;\r\n");
      out.write("\t\tswapText  = formSelect.options[selectedIndex-1].text;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttempValue = selValue;\r\n");
      out.write("\t\ttempText  = selText;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tformSelect.options[selectedIndex].value = swapValue;//selValue=swapValue\r\n");
      out.write("\t\tformSelect.options[selectedIndex].text  = swapText;  \r\n");
      out.write("\t\tformSelect.options[selectedIndex-1].value = tempValue;//swapValue=tempValue\r\n");
      out.write("\t\tformSelect.options[selectedIndex-1].text  = tempText;\r\n");
      out.write("\t\tformSelect.selectedIndex                = selectedIndex-1;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function lower(idx){ ////////////////////////////////// 아래로 내리기 함수\r\n");
      out.write("\r\n");
      out.write("\tselectedForm(idx);\r\n");
      out.write("\tselectedIndex = formSelect.selectedIndex\r\n");
      out.write("\r\n");
      out.write("\tif(selectedIndex==-1){\r\n");
      out.write("\t\talert(\"선택한 메뉴가 없습니다.\"); \r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}else if(selectedIndex+1==formSelect.length){\r\n");
      out.write("\t\talert(\"최하위 메뉴를 선택하셨습니다.\"); \r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tselValue  = formSelect.options[selectedIndex].value;\r\n");
      out.write("\t\tselText   = formSelect.options[selectedIndex].text;\r\n");
      out.write("\r\n");
      out.write("\t\tswapValue = formSelect.options[selectedIndex+1].value;\r\n");
      out.write("\t\tswapText  = formSelect.options[selectedIndex+1].text;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttempValue = selValue;\r\n");
      out.write("\t\ttempText  = selText;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tformSelect.options[selectedIndex].value = swapValue;//selValue=swapValue\r\n");
      out.write("\t\tformSelect.options[selectedIndex].text  = swapText;  \r\n");
      out.write("\t\tformSelect.options[selectedIndex+1].value = tempValue;//swapValue=tempValue\r\n");
      out.write("\t\tformSelect.options[selectedIndex+1].text  = tempText;\r\n");
      out.write("\t\tformSelect.selectedIndex                = selectedIndex+1;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function trim(item){//공백을 제거 하는 트림 함수\r\n");
      out.write("var trimItem\r\n");
      out.write("\ttrimItem = item.replace(/\\s/g, \"\");\r\n");
      out.write("\treturn trimItem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function add_OK(idx){\r\n");
      out.write("\tvar item, reItem \r\n");
      out.write("\titem=document.getElementById(\"text\"+idx)\r\n");
      out.write("\treItem=trim(item.value) // 아이템을 트림함수 돌려서 리플레이스하여 공백 제거\r\n");
      out.write("\titem.value=reItem; // 사용자가 보는 인풋 텍스트 박스에 공백 제거 값 보여주기\r\n");
      out.write("\r\n");
      out.write("\t\tif(idx==1){\r\n");
      out.write("\t\t\tformSelect    = document.menuform.first\r\n");
      out.write("\t\t}else if (idx==2){\r\n");
      out.write("\t\t\tformSelect    = document.menuform.second\r\n");
      out.write("\t\t}else if (idx==3){\r\n");
      out.write("\t\t\tformSelect    = document.menuform.third\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"셀렉트메뉴박스 오류 입니다.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (reItem.length==0){\r\n");
      out.write("\t\t\talert(\"메뉴를 입력하세요\");\r\n");
      out.write("\t\t\titem=document.getElementById(\"text\"+idx)\r\n");
      out.write("\t\t\titem.style.backgroundColor = \"yellow\";\r\n");
      out.write("\t\t\titem.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfor (i=0;i<formSelect.length;i++ ){\r\n");
      out.write("\t\t\tif(formSelect.options[i].value==reItem){\r\n");
      out.write("\t\t\t\talert(\"이미 등록된 값이 있습니다.\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\talert(\"메뉴에[\"+reItem+\"] 추가 합니다.\");\r\n");
      out.write("\tformSelect.options[formSelect.length] = new Option(reItem,reItem);//실제 추가가 일어 난다\t\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function edit_OK(idx){\r\n");
      out.write("\tvar item, reItem \r\n");
      out.write("\titem=document.getElementById(\"text\"+idx)\r\n");
      out.write("\treItem=trim(item.value) // 아이템을 트림함수 돌려서 리플레이스하여 공백 제거\r\n");
      out.write("\titem.value=reItem; // 사용자가 보는 인풋 텍스트 박스에 공백 제거 값 보여주기\r\n");
      out.write("\r\n");
      out.write("\t\tif(idx==1){\r\n");
      out.write("\t\t\tformSelect    = document.menuform.first\r\n");
      out.write("\t\t}else if (idx==2){\r\n");
      out.write("\t\t\tformSelect    = document.menuform.second\r\n");
      out.write("\t\t}else if (idx==3){\r\n");
      out.write("\t\t\tformSelect    = document.menuform.third\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"셀렉트메뉴박스 오류 입니다.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\tselectedIndex = formSelect.selectedIndex\r\n");
      out.write("//\talert(selectedIndex)\r\n");
      out.write("\tif (selectedIndex==-1){\r\n");
      out.write("\t\talert(\"셀렉트 박스에서 수정할 메뉴를 선택하여 주세요\");\r\n");
      out.write("\t\tformSelect.style.backgroundColor = \"yellow\";\r\n");
      out.write("\t\tformSelect.focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tselValue = formSelect.options[selectedIndex].value;\r\n");
      out.write("\t\tselText  = formSelect.options[selectedIndex].text;\r\n");
      out.write("\t\tvar item, reItem \r\n");
      out.write("\t\titem=document.getElementById(\"text\"+idx)\r\n");
      out.write("\t\treItem=trim(item.value) // 아이템을 트림함수 돌려서 리플레이스하여 공백 제거\r\n");
      out.write("\t\titem.value=reItem; // 사용자가 보는 인풋 텍스트 박스에 공백 제거 값 보여주기\r\n");
      out.write("\r\n");
      out.write("\t\t\tif(idx==1){\r\n");
      out.write("\t\t\t\tformSelect    = document.menuform.first\r\n");
      out.write("\t\t\t}else if (idx==2){\r\n");
      out.write("\t\t\t\tformSelect    = document.menuform.second\r\n");
      out.write("\t\t\t}else if (idx==3){\r\n");
      out.write("\t\t\t\tformSelect    = document.menuform.third\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"셀렉트메뉴박스 오류 입니다.\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (reItem.length==0){\r\n");
      out.write("\t\t\t\talert(\"메뉴를 입력하세요\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor (i=0;i<formSelect.length;i++ ){\r\n");
      out.write("\t\t\t\tif(formSelect.options[i].value==reItem){\r\n");
      out.write("\t\t\t\t\talert(\"이미 등록된 값이 있습니다.\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\talert(\"메뉴에[\"+reItem+\"] 수정 합니다.\");\r\n");
      out.write("\t\tformSelect.options[selectedIndex] = new Option(reItem,reItem)\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function del_OK(idx){\r\n");
      out.write("\r\n");
      out.write("\tif(idx==1){\r\n");
      out.write("\t\tformSelect    = document.menuform.first\r\n");
      out.write("\t}else if (idx==2){\r\n");
      out.write("\t\tformSelect    = document.menuform.second\r\n");
      out.write("\t}else if (idx==3){\r\n");
      out.write("\t\tformSelect    = document.menuform.third\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"셀렉트메뉴박스 오류 입니다.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tselectedIndex = formSelect.selectedIndex\r\n");
      out.write("\r\n");
      out.write("\tif (selectedIndex==-1){\r\n");
      out.write("\t\talert(\"셀렉트 박스에서 수정할 메뉴를 선택하여 주세요\");\r\n");
      out.write("\t\tformSelect.style.backgroundColor = \"yellow\";\r\n");
      out.write("\t\tformSelect.focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tformSelect.options[selectedIndex] = null\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<form id=\"menuform\" name=\"menuform\" method=\"post\" action=\"\">\r\n");
      out.write("\r\n");
      out.write("  <p>&nbsp;</p>\r\n");
      out.write(" <p>&nbsp;</p>\r\n");
      out.write(" <table width=\"781\" border=\"1\">\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td width=\"224\" colspan=\"2\"><input type=\"text\" name=\"text1\" id=\"text1\" />\r\n");
      out.write("      <input type=\"button\" name=\"add1\" id=\"add1\" value=\"추가\" onclick=\"add_OK(1)\"/>\r\n");
      out.write("      <input type=\"button\" name=\"edit1\" id=\"edit1\" value=\"수정\" onclick=\"edit_OK(1)\" /></td>\r\n");
      out.write("     <td width=\"254\" colspan=\"2\"><input type=\"text\" name=\"text2\" id=\"text2\" />\r\n");
      out.write("      <input type=\"button\" name=\"add2\" id=\"add2\" value=\"추가\" onclick=\"add_OK(2)\"/>\r\n");
      out.write("      <input type=\"button\" name=\"edit2\" id=\"edit2\" value=\"수정\" onclick=\"edit_OK(2)\" /></td>\r\n");
      out.write("     <td width=\"281\" colspan=\"2\"><input type=\"text\" name=\"text3\" id=\"text3\" />\r\n");
      out.write("      <input type=\"button\" name=\"add3\" id=\"add3\" value=\"추가\" onclick=\"add_OK(3)\"/>\r\n");
      out.write("      <input type=\"button\" name=\"edit3\" id=\"edit3\" value=\"수정\" onclick=\"edit_OK(3)\" /></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td><select name=\"first\" size=\"10\" id=\"first\" style=\"width:200px;\" onchange=\"menu_onclick(1);\">\r\n");
      out.write("       <option value=\"0\">1메뉴</option>\r\n");
      out.write("       <option value=\"1\">2메뉴</option>\r\n");
      out.write("       <option value=\"2\">3메뉴</option>\r\n");
      out.write("       <option value=\"3\">4메뉴</option>\r\n");
      out.write("       <option value=\"4\">5메뉴메뉴의명이 무지 길어져서 영어마을 입소 1박2일 프로그램 공무원 연수 과정 </option>\r\n");
      out.write("       <option value=\"5\">6메뉴</option>\r\n");
      out.write("     </select></td>\r\n");
      out.write("     <td><input type=\"button\" name=\"up\" id=\"up1\" value=\"위로\" onclick=\"upper(1)\" />\r\n");
      out.write("      <input type=\"button\" name=\"down\" id=\"down2\" value=\"아래로\" onclick=\"lower(1)\" /></td>\r\n");
      out.write("     <td>\r\n");
      out.write("       <select name=\"second\" size=\"10\" id=\"second\" style=\"width:200px;\" onChange=\"menu_onclick(2);\">\r\n");
      out.write("         <option value=\"21\">21메뉴</option>\r\n");
      out.write("         <option value=\"22\">22메뉴</option>\r\n");
      out.write("         <option value=\"23\">23메뉴</option>\r\n");
      out.write("         <option value=\"24\">24메뉴</option>\r\n");
      out.write("         <option value=\"25\">25메뉴</option>\r\n");
      out.write("         <option value=\"26\">26메뉴</option>\r\n");
      out.write("       </select></td>\r\n");
      out.write("     <td><input type=\"button\" name=\"up2\" id=\"up2\" value=\"위로\" onclick=\"upper(2)\" />\r\n");
      out.write("      <input type=\"button\" name=\"down2\" id=\"down2\" value=\"아래로\" onclick=\"lower(2)\" /></td>\r\n");
      out.write("     <td>\r\n");
      out.write("         <select name=\"third\" size=\"10\" id=\"third\" style=\"width:200px;\" onChange=\"menu_onclick(3);\">\r\n");
      out.write("           <option value=\"31\">31메뉴</option>\r\n");
      out.write("           <option value=\"32\">32메뉴</option>\r\n");
      out.write("           <option value=\"33\">33메뉴</option>\r\n");
      out.write("           <option value=\"34\">34메뉴</option>\r\n");
      out.write("           <option value=\"35\">35메뉴</option>\r\n");
      out.write("           <option value=\"36\">36메뉴</option>\r\n");
      out.write("         </select>     </td>\r\n");
      out.write("     <td><input type=\"button\" name=\"up3\" id=\"up3\" value=\"위로\" onclick=\"upper(3)\" />\r\n");
      out.write("      <input type=\"button\" name=\"down3\" id=\"down3\" value=\"아래로\" onclick=\"lower(3)\" /></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td colspan=\"2\"><input type=\"button\" name=\"del1\" id=\"del\" value=\"삭제\" onClick=\"del_OK(1)\" /></td>\r\n");
      out.write("     <td colspan=\"2\"><input type=\"button\" name=\"del2\" id=\"del2\" value=\"삭제\" onclick=\"del_OK(2)\" /></td>\r\n");
      out.write("     <td colspan=\"2\"><input type=\"button\" name=\"del3\" id=\"del3\" value=\"삭제\" onclick=\"del_OK(3)\" /></td>\r\n");
      out.write("   </tr>\r\n");
      out.write(" </table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /header/header.jsp(49,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("review");
      // /header/header.jsp(49,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/header/header.jsp(49,10) '${nameis.review}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${nameis.review}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write(" 가능 그러나 review가 아닌 info로 가져와야됨\r\n");
            out.write("    \t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.restno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.restname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_u_005fisLogin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  u:isLogin
    org.apache.jsp.tag.web.isLogin_tag _jspx_th_u_005fisLogin_005f0 = new org.apache.jsp.tag.web.isLogin_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_u_005fisLogin_005f0);
    try {
      _jspx_th_u_005fisLogin_005f0.setJspContext(_jspx_page_context);
      _jspx_th_u_005fisLogin_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_u_005fisLogin_005f0, null));
      _jspx_th_u_005fisLogin_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_u_005fisLogin_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /header/header.jsp(80,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.admin ==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /header/header.jsp(82,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.admin ==0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                \t<li class=\"list-item\"><a href=\"mypage.go\">마이페이지</a></li>\r\n");
          out.write("                \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_u_005fnotLogin_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  u:notLogin
    org.apache.jsp.tag.web.notLogin_tag _jspx_th_u_005fnotLogin_005f0 = new org.apache.jsp.tag.web.notLogin_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_u_005fnotLogin_005f0);
    try {
      _jspx_th_u_005fnotLogin_005f0.setJspContext(_jspx_page_context);
      _jspx_th_u_005fnotLogin_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_u_005fnotLogin_005f0, null));
      _jspx_th_u_005fnotLogin_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_u_005fnotLogin_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /header/header.jsp(103,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("review");
      // /header/header.jsp(103,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/header/header.jsp(103,4) '${nameis.review}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${nameis.review}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /header/header.jsp(103,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("i");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t<li><a href=\"info.go?site=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.restno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.restname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.restis}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("점</a></li>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write(" <!-- 로그인시 -->\r\n");
      out.write("                \t");
      if (_jspx_meth_c_005fif_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("                \t");
      if (_jspx_meth_c_005fif_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"list-item\"><a href=\"logout.go\">로그아웃</a></li>\r\n");
      out.write("                ");
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write(" <!--미로그인시--> \r\n");
      out.write("                \t<li class=\"list-item\"><a href=\"admin.go\">관리자페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<!-- <li class=\"list-item\"><a href=\"login.go\">로그인</a></li> -->\r\n");
      out.write("\t\t\t\t\t<li class=\"list-item\"><a href=\"join.go\">회원가입</a></li>\r\n");
      out.write("                ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
