/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-05-22 07:05:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.recommend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class re_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/hong/Desktop/hyusikpro/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pprr/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1590049336297L));
    _jspx_dependants.put("/header/header.jsp", Long.valueOf(1590130024990L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#rank {width: 200px;position: relative;top: -35px;left: 940px;}\r\n");
      out.write("#rank-list {overflow: hidden;width: 300px;height: 20px;margin: 0;}\r\n");
      out.write("#rank-list dd {position: relative;margin: 0;}\r\n");
      out.write("#rank-list ol {position: absolute;top: 0;left: 0;margin: 0;padding: 0;list-style-type: none;}\r\n");
      out.write("#rank-list li {height: 20px;line-height: 20px;}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("    var count = $('#rank-list li').length;\r\n");
      out.write("    var height = $('#rank-list li').height();\r\n");
      out.write("\r\n");
      out.write("    function step(index) {\r\n");
      out.write("        $('#rank-list ol').delay(2000).animate({\r\n");
      out.write("            top: -height * index,\r\n");
      out.write("        }, 500, function() {\r\n");
      out.write("            step((index + 1) % count);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    step(1);\r\n");
      out.write("});\r\n");
      out.write("function ranking(){\r\n");
      out.write("\tif(location=='http://localhost:8090/' || location=='http://localhost:8090/index.jsp'){\r\n");
      out.write("\tlocation.replace(\"/main.go\");}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/header/header_style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"ranking()\">\r\n");
      out.write("<header class=\"body\">\r\n");
      out.write("<form name=\"form1\" action=\"");
      out.print(request.getContextPath());
      out.write("/info.go\" method=\"get\">\r\n");
      out.write("<!-- target=\"_blank\" 클릭하면 새창 -->\r\n");
      out.write("<span class=\"logo\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/main.go\">휴~ 식</a></span>\t\r\n");
      out.write("  <div id=\"choice\">\r\n");
      out.write("  <!-- http://localhost:8090/kim/header/header_login.jsp?site=? -->\r\n");
      out.write("    <select name=\"site\" id=\"site\" style=\"width:50%;height:30px;\">\r\n");
      out.write("    \t<option selected>선택하세요</option>\r\n");
      out.write("        \t<option value=\"1\">서울 만남의 광장 부산방향</option>\r\n");
      out.write("            <option value=\"2\">죽전휴게소 서울방향</option>\r\n");
      out.write("            <option value=\"3\">기흥휴게소 부산방향</option>\r\n");
      out.write("            <option value=\"4\">안성휴게소 서울방향</option>\r\n");
      out.write("            <option value=\"5\">입장거봉포도휴게소 서울방향</option>\r\n");
      out.write("            <option value=\"6\">망향휴게소 부산방향</option>\r\n");
      out.write("            <option value=\"7\">천안삼거리휴게소 서울방향</option>\r\n");
      out.write("            <option value=\"8\">천안호두휴게소 부산방향</option>\r\n");
      out.write("            <option value=\"9\">청주휴게소 서울방향</option>\r\n");
      out.write("            <option value=\"10\">옥산휴게소 부산방향</option>\r\n");
      out.write("            <option value=\"11\">죽암휴게소 서울방향</option>\r\n");
      out.write("            <option value=\"12\">죽암휴게소 부산방향</option>\r\n");
      out.write("            <option value=\"13\">신탄진휴게소 서울방향</option>\r\n");
      out.write("    </select>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"찾기\" style=\"height:30px;\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<nav class=\"nav\">\r\n");
      out.write("\t\t\t<ul class=\"list\">\r\n");
      out.write("\t\t\t\t<!-- filter설정하기 -->\r\n");
      out.write("\t\t\t\t<li class=\"list-item\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/notice/list.go\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"list-item\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/road/roadsa.jsp\">사고 상황</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"list-item\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/road.go\">공사 상황</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"list-item\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/recommend/re.jsp\">추천휴게소</a></li>\r\n");
      out.write("                <li class=\"list-item\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/oilprice.go\">추천주유소</a></li>\r\n");
      out.write("                <li class=\"list-item\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/review/review_list.jsp\">리뷰</a></li>\r\n");
      out.write("                \r\n");
      out.write("                ");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /header/header.jsp(76,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty AUTHUSER }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write(" <!-- 로그인시 -->\r\n");
            out.write("                \t");
            //  c:if
            org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
            boolean _jspx_th_c_005fif_005f1_reused = false;
            try {
              _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
              // /header/header.jsp(77,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AUTHUSER.admin ==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
              if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("                \t\t<li class=\"list-item\"><a href=\"");
                  out.print(request.getContextPath());
                  out.write("/admin.go\">관리자</a></li>\r\n");
                  out.write("                \t");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
              _jspx_th_c_005fif_005f1_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
            }
            out.write("\r\n");
            out.write("                \t");
            //  c:if
            org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
            boolean _jspx_th_c_005fif_005f2_reused = false;
            try {
              _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
              // /header/header.jsp(80,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AUTHUSER.admin ==0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
              if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("                \t\t<li class=\"list-item\"><a href=\"");
                  out.print(request.getContextPath());
                  out.write("/myPage.go\">마이페이지</a></li>\r\n");
                  out.write("                \t");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
              _jspx_th_c_005fif_005f2_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t<li class=\"list-item\"><a href=\"");
            out.print(request.getContextPath());
            out.write("/logout.go\">로그아웃</a></li>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("                ");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f3_reused = false;
      try {
        _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f3.setParent(null);
        // /header/header.jsp(85,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty AUTHUSER }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
        if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write(" <!--미로그인시--> \r\n");
            out.write("\t\t\t\t\t<li class=\"list-item\"><a href=\"");
            out.print(request.getContextPath());
            out.write("/login.go\">로그인</a></li>\r\n");
            out.write("\t\t\t\t\t<li class=\"list-item\"><a href=\"");
            out.print(request.getContextPath());
            out.write("/join.go\">회원가입</a></li>\r\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
        _jspx_th_c_005fif_005f3_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
      }
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"rank\">\r\n");
      out.write("\t\t<dl id=\"rank-list\">\r\n");
      out.write("\t\t\t<dd>\r\n");
      out.write("\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t<li>휴게소 만족도 순위</li>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </ol>\r\n");
      out.write("            </dd>\r\n");
      out.write("        </dl>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>추천 페이지</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.2.0.min.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("  var ex_show = $('.ex_show');\r\n");
      out.write("  var ex_hide = $('.ex_hide');\r\n");
      out.write("  var ex_box = $('.ex_box');\r\n");
      out.write("  ex_show.click(function(){\r\n");
      out.write("    ex_box.fadeIn();\r\n");
      out.write("  });\r\n");
      out.write("  ex_hide.click(function(){\r\n");
      out.write("    ex_box.fadeOut();\r\n");
      out.write("  });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("      $('h1').hover(function(){\r\n");
      out.write("        $(this).css('background','yellow')\r\n");
      out.write("    },function(){\r\n");
      out.write("        $(this).css('background','white')\r\n");
      out.write("    })\r\n");
      out.write("    $('h2').hover(\r\n");
      out.write("    function(){$(this).addClass('hugeso')},\r\n");
      out.write("    function(){$(this).removeClass('hugeso')})\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".ex_show{float:left;margin-right:20px;cursor:pointer}\r\n");
      out.write(".ex_hide{float:left;cursor:pointer}\r\n");
      out.write(".ex_box{clear:both;\r\n");
      out.write(" float:left;\r\n");
      out.write(" width:100px;\r\n");
      out.write(" height:50px;\r\n");
      out.write(" background-color:red;\r\n");
      out.write(" border:1px solid blue;\r\n");
      out.write(" margin:50px;\r\n");
      out.write("   border-radius:10px}\r\n");
      out.write(".hugeso {background:pink}  \r\n");
      out.write(".rounded {\r\n");
      out.write("  width: 700px;\r\n");
      out.write("  background-color: #ddf;\r\n");
      out.write("  border:2px solid #abc;\r\n");
      out.write("  padding:1em;\r\n");
      out.write("  line-height: 1em;\r\n");
      out.write("  border-radius:0.2em;\r\n");
      out.write("  -moz-border-radius: 0.2em;\r\n");
      out.write("  -webkit-border-radius: 0.5em;\r\n");
      out.write("  font-size:1.4em;\r\n");
      out.write("  margin-left: 470px;\r\n");
      out.write("  }\r\n");
      out.write(".a {\r\n");
      out.write("        margin: 0px 0px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 80px;\r\n");
      out.write("        color: #4969F2;\r\n");
      out.write("        }  \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div align=\"center\" style=\"a\"><strong>휴게소 맛집 랭킹</strong></div>\r\n");
      out.write("\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<a href=\"#none\" onclick=\"fn()\">\r\n");
      out.write("\t\t\t\t<h1>1. 화성휴게소</h1></a>\r\n");
      out.write("\t\t    <h3>이영자 추천 맛집</h3>\r\n");
      out.write("\t\t\t<div id=\"a\">\r\n");
      out.write("\t\t\t\t<p class=\"a\" >\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-smile-o\" aria-hidden=\"true\"></i>\t\t\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\tfunction fn() {\r\n");
      out.write("\t\t\t\t\t$(\"#a\").css(\"position\",\"relative\");\r\n");
      out.write("\t\t\t\t\tif($(\"#a\").css(\"opacity\") == 1)\r\n");
      out.write("\t\t\t\t\t$(\"#a\").animate({opacity : 0,top:\"+=500\",left:\"+=500\"},1000);\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t$(\"#a\").animate({opacity : 1,top:\"0\",left:\"0\"},1000);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t<h1>2. 금강휴게소</h1>\r\n");
      out.write("\t<h1>3. 동해휴게소</h1>\r\n");
      out.write("\t<h2>4. 단양휴게소</h2>\r\n");
      out.write("\t<h2>5. 정읍 녹두장군휴게소</h2>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    jQuery(document).ready(function() {\r\n");
      out.write("        jQuery(\"#btn\").click(function() {\r\n");
      out.write("            if(jQuery(\"#displayDiv\").css(\"display\") == \"none\") {\r\n");
      out.write("                jQuery(\"#displayDiv\").fadeIn();}\r\n");
      out.write("            else {jQuery(\"#displayDiv\").fadeOut();}\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("    <h1>휴게소 테마 소개</h1>\r\n");
      out.write("    <hr/>  \r\n");
      out.write("    <div id=\"displayDiv\">\r\n");
      out.write("        <img src=\"https://post-phinf.pstatic.net/MjAxNzAzMjhfNzUg/MDAxNDkwNjY3NzQyMDUz.SwuuF3AkKeCURuoNetbdMtVwbkKvlF71ggwdea7BAt4g.wJox2lwR1rzTBdYsKBGJwTj9rEUYQfu-fCPq51Lgw0Eg.JPEG/1.jpg?type=w1200\" width=\"400\" height=\"300\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <button type=\"button\" id=\"btn\">1위 휴게소 사진보기</button>\r\n");
      out.write("    <div>\r\n");
      out.write("    \t휴게소명 : 마장 프리미엄 휴게소<br/>\r\n");
      out.write("    \t휴게소 테마 : 프리미엄 테마<br/>\r\n");
      out.write("    \t휴게소 위치 : 중부고속도로 - 경기 이천시 마장면 중부고속도로 82\r\n");
      out.write("    \t테마설명 : 중부고속도로의 자랑! 국내 최대 규모 프리미엄 휴게소로 인증받은 마장휴게소에 들러보자! <br/>\r\n");
      out.write("    \t2만 7490㎡의 총면적에 지하 1층, 지상 3층으로 구성된 마장 프리미엄 휴게소는 스타벅스, 맥도날드, 롯데마트, 파리바게뜨 등의 프랜차이즈와 각종 브랜드 의류 매장, 공연장이 입점해 있어 <br/> \r\n");
      out.write("    \t깜빡 잊고 안 가져온 물품을 사거나 친환경 쉼터에서 장거리 운전의 피로를 달래고 답답해하는 아이들과 공연을 즐길 수 있는 최고의 복합문화휴식공간으로 자리 잡고 있다. <br/> \r\n");
      out.write("    \t주말에는 하루 2회씩 퓨전 국악, 마술, 아동극, 관악 4중주 등의 문화공연이 펼쳐지기도 하니 잠시 들르는 휴게소가 아니라 여행의 목적지가 되기도 한다.\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    jQuery(document).ready(function() {\r\n");
      out.write("        jQuery(\"#bttn\").click(function() {\r\n");
      out.write("            if(jQuery(\"#displayDivb\").css(\"display\") == \"none\") {\r\n");
      out.write("                jQuery(\"#displayDivb\").fadeIn();}\r\n");
      out.write("            else {jQuery(\"#displayDivb\").fadeOut();}\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("    <hr/>\r\n");
      out.write("    <div id=\"displayDivb\">\r\n");
      out.write("        <img src=\"https://www.ikld.kr/news/photo/201502/43817_21838_3340.jpg\" width=\"400\" height=\"300\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <button type=\"button\" id=\"bttn\">2위 휴게소 사진 보기</button>\r\n");
      out.write("    <div>\r\n");
      out.write("    \t휴게소명 : 덕평자연휴게소<br/>\r\n");
      out.write("    \t휴게소 테마 : 자연 테마<br/>\r\n");
      out.write("    \t테마설명:덕평휴게소는 소고기국밥 판매량 1위라는 타이틀을 가지고 있다. 매년 17만 그릇이 넘는 소고기국밥이 팔리고 있지만 덕평휴게소의 매력은 먹거리에만 한정되어 있지는 않다.<br/> \r\n");
      out.write("    \t2007년 한국건축문화대상을 받을 만큼 수려한 외관을 자랑하며 자연을 그대로 담은 러브가든과 허브 정원, 각종 예술 작품과 함께 생태공원이 조성되어 있어 진정한 의미의 힐링을 할 수 있는 곳이다.<br/> \r\n");
      out.write("    \t또 국내 최초의 애견 테마파크 '달려라 코코'가 있어 아이들과 애견 가족에게도 높은 인기를 누리고 있다.\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    jQuery(document).ready(function() {\r\n");
      out.write("        jQuery(\"#btttn\").click(function() {\r\n");
      out.write("            if(jQuery(\"#displayDivbb\").css(\"display\") == \"none\") {\r\n");
      out.write("                jQuery(\"#displayDivbb\").fadeIn();}\r\n");
      out.write("            else {jQuery(\"#displayDivbb\").fadeOut();}\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("    <hr/>\r\n");
      out.write("    <div id=\"displayDivbb\">\r\n");
      out.write("        <img src=\"https://img1.daumcdn.net/thumb/R720x0.q80/?scode=mtistory2&fname=http%3A%2F%2Fcfile4.uf.tistory.com%2Fimage%2F9907853D5C206EBC2472E1\" width=\"400\" height=\"300\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <button type=\"button\" id=\"btttn\">3위 휴게소 사진 보기</button>\r\n");
      out.write("    <div>\r\n");
      out.write("    \t휴게소명 : 안성휴게소<br/>\r\n");
      out.write("    \t휴게소 테마 : 맛집 테마<br/>\r\n");
      out.write("    \t테마설명:호두과자, 우동, 통감자 등 고속도로 휴게소 음식 하면 가장 먼저 떠오르는 것들이 있다. <br/>\r\n");
      out.write("    \t이상하게 배가 고프지 않아도 휴게소에 들르면 꼭 무언가를 허겁지겁 먹으며 다시 차에 오르는 재미를 누리고 싶어진다. <br/>\r\n");
      out.write("    \t휴게소 음식이 대부분 거기서 거기라지만 분명 맛으로 경쟁하는 맛집 휴게소들이 존재한다. <br/>\r\n");
      out.write("    \t대표적인 곳이 바로 경부고속도로 부산 방향의 안성휴게소. ‘안성국밥’이라고 하는 새빨간 국물의 소고기국밥은 안 먹어보면 서러울 만큼 최고의 맛을 자랑한다. <br/>\r\n");
      out.write("    \t서울 방향 안성휴게소에서도 소고기국밥을 팔지만, 국물이 하얀 '안성 옥국밥'이기에 하행선 안성휴게소에서만 판매하는 '안성국밥'을 기억해주시기 바란다.\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /header/header.jsp(100,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("review");
      // /header/header.jsp(100,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/header/header.jsp(100,4) '${nameis.review}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${nameis.review}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /header/header.jsp(100,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("i");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t<li><a href=\"info.go?site=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.restno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.restname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.restis}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("점</a></li>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
